tap "apple/apple", "http://github.com/apple/homebrew-apple"
brew "antidote"
brew "awscli"
brew "cocoapods"
brew "colima", restart_service: :changed
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "doctl"
brew "fastfetch"
brew "ffmpeg"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "git"
brew "gnupg"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "neovim"
brew "nvm"
brew "ollama", restart_service: :changed
brew "starship"
brew "stern"
brew "stripe-cli"
brew "vercel-cli"
brew "watchman"
brew "xh"
cask "1password"
cask "affinity"
cask "android-studio"
cask "brave-browser"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "cursor"
cask "cyberduck"
cask "discord"
cask "figma"
cask "firefox"
cask "font-maple-mono-nf"
cask "gcloud-cli"
cask "ghostty"
cask "istat-menus"
cask "lens"
cask "nordvpn"
cask "onlyoffice"
cask "phpstorm"
cask "postman"
cask "raycast"
cask "sf-symbols"
cask "slack"
cask "sublime-text"
cask "tableplus"
cask "tailscale-app"
cask "telegram"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zulu@17"
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Permute 3", id: 1444998321
mas "Xcode", id: 497799835
vscode "anthropic.claude-code"
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "editorconfig.editorconfig"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "ms-playwright.playwright"
vscode "prisma.prisma"
vscode "thang-nm.catppuccin-perfect-icons"
vscode "xyz.local-history"
